### ISSUE TITLE
Super nice!

### ISSUE THREAD

**Issue by schroef** [Margaret2/pantone-colors#6]
Wow this is super nice! How did you collect all these numbers?
Can i ask why all the colors are also added in all kinds of file formats?

I was looking for a database with PMS numbers so i could perhaps update [this addon](https://b3d.interplanety.org/en/blender-add-on-color-matching/)

After some googling i found this addon. Do you mind if give it a go with your numbers. I will mention you and your website ofcourse

**Comment by Margaret2** [comment]
Thanks! They have [this tool](https://www.pantone.com/color-intelligence/color-education/x-ref) on their website - if you open the color picker, there's a list of all colors and you can just inspect it and get all the hex values from there.

I thought putting them in different file formats might be useful to people, that's all ¯\\_(ツ)_/¯

But yeah, I'm not really updating it anymore so feel free to fork it and modify it, or use the numbers however you want :)

**Comment by schroef** [comment]
Okay great, I got it working now and also was able to add RGB values. I'll link you GitHub / URL in the source code.

Still need to check some code to convert it to CMYK. However I believe converting them doesn't give the "official" CMYK values. Not 100% sure about that part

**Comment by schroef** [comment]
Thanks for that top of the ref tool, now i think i can manage to get the others :)

**Comment by ldo** [comment]
I think the whole point about spot colours is they cannot have any accurate process colour (CMYK) representation.
